### PR TITLE
refactor: change package type module from commonjs

### PR DESCRIPTION
**Pull request by nadeem-cs**

### CODE REVIEW

**Comment by timbenniks** [comment]
@nadeem-cs did you test it works in Nuxt, Astro and Remix? The test should be simple enough, you import the package and there are no errors compiling the project.

**Review by harshithad0703 — DISMISSED** [review]
Approved

**Comment by nadeem-cs** [comment]
@timbenniks It works with Nuxt. However some more changes needed to be done for ESM build. Attached a ticket on JIRA for the same. Merging this for now. The release will be done after the attached ticket is resolved. Thanks.

**Review by harshithad0703 — APPROVED** [review]
approved

**Pull request merged**
